# 日本語のコメントを許容
Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

  # 無効化するファイルの設定
AllCops:
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'

# 空メソッドのスタイル
Style/EmptyMethod: 
  EnforcedStyle: expanded

# 1行あたりの文字数
Layout/LineLength:
  Max: 100

# private,protectedのメソッドは一段深くインデントさせるべき
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

# ABC Size Checkを緩くする
Metrics/AbcSize:
  Max: 30

# classes/modulesを書くときはnestedじゃなくてコンパクトにする
Style/ClassAndModuleChildren:
  EnforcedStyle: compact