# 日本語のコメントを許容
Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

  # 無効化するファイルの設定
AllCops:
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'

# 空メソッドのスタイル
Style/EmptyMethod: 
  EnforcedStyle: expanded

# 1行あたりの文字数
Layout/LineLength:
  Max: 100